"""Environment setup utilities.

Provides helpers to configure the runtime environment for a given cluster,
including setting environment variables, validating paths exist, and
generating activation scripts for interactive or batch use.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

from neurolab.jobs.config import ClusterConfig, auto_detect_cluster


class EnvironmentManager:
    """Manages runtime environment configuration for a cluster.

    This class applies environment variables, validates filesystem paths,
    and can generate shell scripts for SLURM job preambles.

    Usage:
        from neurolab.jobs import EnvironmentManager, get_cluster

        env = EnvironmentManager(get_cluster("expanse"))
        env.apply()          # Sets os.environ for current process
        env.validate()       # Checks that key paths exist

        # Or auto-detect:
        env = EnvironmentManager.from_auto_detect()
    """

    def __init__(self, cluster: ClusterConfig) -> None:
        self.cluster = cluster

    @classmethod
    def from_auto_detect(cls) -> EnvironmentManager:
        """Create an EnvironmentManager by auto-detecting the current cluster."""
        return cls(auto_detect_cluster())

    def apply(self) -> None:
        """Apply cluster environment variables to the current process.

        Sets all env_vars from the cluster config into os.environ.
        Existing values are NOT overwritten unless force=True.
        """
        for key, value in self.cluster.env_vars.items():
            # Expand ~ and $VAR references in values
            expanded = os.path.expandvars(os.path.expanduser(value))
            if key not in os.environ:
                os.environ[key] = expanded

    def apply_force(self) -> None:
        """Apply cluster environment variables, overwriting existing values."""
        for key, value in self.cluster.env_vars.items():
            expanded = os.path.expandvars(os.path.expanduser(value))
            os.environ[key] = expanded

    def validate(self, strict: bool = False) -> list[str]:
        """Validate that key filesystem paths exist.

        Args:
            strict: If True, raise an error on missing paths. If False,
                    return a list of warnings.

        Returns:
            List of warning messages for missing paths.
        """
        warnings: list[str] = []
        paths = self.cluster.paths

        for label, path_str in [
            ("data", paths.data),
            ("results", paths.results),
            ("conda_envs", paths.conda_envs),
            ("cache", paths.cache),
        ]:
            expanded = Path(os.path.expanduser(path_str))
            if not expanded.exists():
                msg = f"[{self.cluster.name}] Path '{label}' does not exist: {expanded}"
                warnings.append(msg)

        if self.cluster.conda_env:
            conda_path = Path(self.cluster.conda_env)
            if not conda_path.exists():
                msg = f"[{self.cluster.name}] Conda env not found: {conda_path}"
                warnings.append(msg)

        if strict and warnings:
            raise EnvironmentError(
                f"Environment validation failed for '{self.cluster.name}':\n"
                + "\n".join(f"  - {w}" for w in warnings)
            )

        return warnings

    def ensure_dirs(self) -> None:
        """Create output directories (results, scratch, cache) if they don't exist."""
        paths = self.cluster.paths
        for path_str in [paths.results, paths.scratch, paths.cache]:
            expanded = Path(os.path.expanduser(path_str))
            expanded.mkdir(parents=True, exist_ok=True)

    def write_activation_script(self, path: str | Path) -> Path:
        """Write a shell activation script for this cluster.

        The script can be sourced in interactive sessions or SLURM jobs:
            source /path/to/activate_expanse.sh

        Args:
            path: Output path for the script.

        Returns:
            The path to the written script.
        """
        out = Path(path)
        content = (
            f"#!/usr/bin/env bash\n"
            f"# Auto-generated by neurolab-config for cluster: {self.cluster.name}\n"
            f"# Source this file to set up the environment:\n"
            f"#   source {out}\n\n"
            f"{self.cluster.render_env_setup()}\n"
        )
        out.write_text(content)
        out.chmod(0o755)
        return out
